allowable_features_v0 = {
    "possible_atomic_num_list": list(range(0, 119)) + ["misc"],
    "possible_chirality_list": [
        "CHI_UNSPECIFIED",
        "CHI_TETRAHEDRAL_CW",
        "CHI_TETRAHEDRAL_CCW",
        "CHI_TRIGONALBIPYRAMIDAL",
        "CHI_OCTAHEDRAL",
        "CHI_SQUAREPLANAR",
        "CHI_OTHER",
    ],
    "possible_degree_list": list(range(99)) + ["misc"],
    "possible_formal_charge_list": [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, "misc"],
    "possible_numH_list": [0, 1, 2, 3, 4, 5, 6, 7, 8, "misc"],
    "possible_number_radical_e_list": [0, 1, 2, 3, 4, "misc"],
    "possible_hybridization_list": ["SP", "SP2", "SP3", "SP3D", "SP3D2", "misc"],
    "possible_is_aromatic_list": [False, True],
    "possible_is_in_ring_list": [False, True],
    "possible_bond_type_list": ["SINGLE", "DOUBLE", "TRIPLE", "AROMATIC", "misc"],
    "possible_bond_stereo_list": [
        "STEREONONE",
        "STEREOZ",
        "STEREOE",
        "STEREOCIS",
        "STEREOTRANS",
        "STEREOANY",
    ],
    "possible_is_conjugated_list": [False, True],
    "possible_bond_dir_list": [
        "NONE", 
        "BEGINWEDGE", 
        "BEGINDASH", 
        "ENDDOWNRIGHT",
        "ENDUPRIGHT", 
        "EITHERDOUBLE", 
        "R_BEGINWEDGE", 
        "R_BEGINDASH", 
        "R_ENDDOWNRIGHT",
        "R_ENDUPRIGHT", 
        "R_EITHERDOUBLE", 
        "UNKNOWN"
    ],
}


allowable_features_v1 = {
    "possible_atomic_num_list": list(range(0, 119)) + ["misc"],
    "possible_chirality_list": [
        "CHI_UNSPECIFIED",
        "CHI_TETRAHEDRAL_CW",
        "CHI_TETRAHEDRAL_CCW",
        "CHI_TRIGONALBIPYRAMIDAL",
        "CHI_OCTAHEDRAL",
        "CHI_SQUAREPLANAR",
        "CHI_OTHER",
        "CHI_TETRAHEDRAL",
        "CHI_ALLENE",
    ],
    "possible_degree_list": list(range(99)) + ["misc"],
    # change
    "possible_formal_charge_list": [i - 8 for i in range(17)] + ["misc"],
    "possible_numH_list": [0, 1, 2, 3, 4, 5, 6, 7, 8, "misc"],
    "possible_number_radical_e_list": [0, 1, 2, 3, 4, "misc"],
    "possible_hybridization_list": [
        "SP",
        "SP2",
        "SP3",
        "SP3D",
        "SP3D2",
        "S",
        "SP2D",
        "OTHER",
        "UNSPECIFIED",
        "misc",
    ],
    "possible_is_aromatic_list": [False, True],
    "possible_is_in_ring_list": [False, True],
    "possible_bond_type_list": [
        "SINGLE",
        "DOUBLE",
        "TRIPLE",
        "AROMATIC",
        "UNSPECIFIED",
        "QUADRUPLE",
        "QUINTUPLE",
        "HEXTUPLE",
        "ONEANDAHALF",
        "TWOANDAHALF",
        "THREEANDAHALF",
        "FOURANDAHALF",
        "FIVEANDAHALF",
        "IONIC",
        "HYDROGEN",
        "THREECENTER",
        "DATIVEONE",
        "DATIVE",
        "DATIVEL",
        "DATIVER",
        "OTHER",
        "ZERO",
        "misc",
    ],
    "possible_bond_stereo_list": [
        "STEREONONE",
        "STEREOZ",
        "STEREOE",
        "STEREOCIS",
        "STEREOTRANS",
        "STEREOANY",
    ],
    "possible_is_conjugated_list": [False, True],
    "possible_bond_dir_list": [
        "NONE", 
        "BEGINWEDGE", 
        "BEGINDASH", 
        "ENDDOWNRIGHT",
        "ENDUPRIGHT", 
        "EITHERDOUBLE", 
        "R_BEGINWEDGE", 
        "R_BEGINDASH", 
        "R_ENDDOWNRIGHT",
        "R_ENDUPRIGHT", 
        "R_EITHERDOUBLE", 
        "UNKNOWN"
    ],
}


allowable_features_v2 = {
    "possible_atomic_num_list": list(range(0, 119)) + ["misc"],
    # https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html
    "possible_chirality_list": [
        "CHI_UNSPECIFIED",
        "CHI_TETRAHEDRAL_CW",
        "CHI_TETRAHEDRAL_CCW",
        "CHI_TRIGONALBIPYRAMIDAL",
        "CHI_OCTAHEDRAL",
        "CHI_SQUAREPLANAR",
        "CHI_OTHER",
        "CHI_TETRAHEDRAL",
        "CHI_ALLENE",
        "misc",
    ],
    "possible_degree_list": list(range(31)) + ["misc"],
    # change
    "possible_formal_charge_list": [i - 31 // 2 for i in range(31)] + ["misc"],
    "possible_numH_list": list(range(31)) + ["misc"],
    "possible_number_radical_e_list": list(range(31)) + ["misc"],
    # https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a58e40e30db6b42826243163175cac976
    "possible_hybridization_list": [
        "SP",
        "SP2",
        "SP3",
        "SP3D",
        "SP3D2",
        "S",
        "SP2D",
        "OTHER",
        "UNSPECIFIED",
        "misc",
    ],
    "possible_is_aromatic_list": [False, True],
    "possible_is_in_ring_list": [False, True],
    # https://www.rdkit.org/docs/cppapi/classRDKit_1_1Bond.html#a2c93af0aeb3297ee77b6afdc27b68d6f
    "possible_bond_type_list": [
        "SINGLE",
        "DOUBLE",
        "TRIPLE",
        "AROMATIC",
        "UNSPECIFIED",
        "QUADRUPLE",
        "QUINTUPLE",
        "HEXTUPLE",
        "ONEANDAHALF",
        "TWOANDAHALF",
        "THREEANDAHALF",
        "FOURANDAHALF",
        "FIVEANDAHALF",
        "IONIC",
        "HYDROGEN",
        "THREECENTER",
        "DATIVEONE",
        "DATIVE",
        "DATIVEL",
        "DATIVER",
        "OTHER",
        "ZERO",
        "misc",
    ],
    # https://www.rdkit.org/docs/cppapi/classRDKit_1_1Bond.html#ae91dd8e72b495a48f46775c874882165
    "possible_bond_stereo_list": [
        "STEREONONE",
        "STEREOZ",
        "STEREOE",
        "STEREOCIS",
        "STEREOTRANS",
        "STEREOANY",
    ],
    "possible_is_conjugated_list": [False, True],
    "possible_bond_dir_list": [
        "NONE", 
        "BEGINWEDGE", 
        "BEGINDASH", 
        "ENDDOWNRIGHT",
        "ENDUPRIGHT", 
        "EITHERDOUBLE", 
        "R_BEGINWEDGE", 
        "R_BEGINDASH", 
        "R_ENDDOWNRIGHT",
        "R_ENDUPRIGHT", 
        "R_EITHERDOUBLE", 
        "UNKNOWN"
    ],
}
# v1 for paper 50k full
flag_new_allowable_features = "v2"
if flag_new_allowable_features == "v2":
    allowable_features = allowable_features_v2
elif flag_new_allowable_features == "v1":
    allowable_features = allowable_features_v1
else:
    allowable_features = allowable_features_v0
print("flag_new_allowable_features", flag_new_allowable_features)
